[build]
  command = "npm run build:netlify"
  publish = "out"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://gregarious-sawine-ed40c7.netlify.app"
  NEXT_PUBLIC_DOMAIN = "gregarious-sawine-ed40c7.netlify.app"
  NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; img-src 'self' data: blob: *.netlify.app images.unsplash.com; media-src 'self' *.netlify.app; connect-src 'self' *.netlify.app;"

# Specific redirects for static assets
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Handle _next static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# For direct page routes - try serving the HTML file directly
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  force = false

# For directory routes - serve index.html from the directory
[[redirects]]
  from = "/*/"
  to = ":splat/index.html"
  status = 200
  force = false
  
# Only as a fallback when nothing else matches
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false