[build]
  command = "npm run build"
  publish = "out"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://gregarious-sawine-ed40c7.netlify.app"
  NEXT_PUBLIC_DOMAIN = "gregarious-sawine-ed40c7.netlify.app"
  NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; img-src 'self' data: blob: *.netlify.app images.unsplash.com; media-src 'self' *.netlify.app; connect-src 'self' *.netlify.app;"

# These redirects ensure that all routes work with Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 